version: '3.7'

services:
  asim0v-executor-container:
    image: asim0v-executor:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/asim0v-executor
    ports:
      - "9090:9090"
      - "9091:9091"
    networks: 
      - dataloader_elastic
networks: 
  dataloader_elastic:
    external: true