version: '3.7'

services:
  asim0v-executor-container:
    image: asim0v-executor:1
    build:
      context: ./
      dockerfile: Dockerfile
    #mount local folder inside container
    volumes:
      - ./:/data/asim0v-executor
    #enable remote debug, not needed for live reload
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081 -Xms512m -Xmx1024m -jar /app/executor.jar
    ports:
      - "9090:9090"
      - "9091:9091"
    networks: 
      - elastic
networks: 
  elastic:
    driver: bridge
